

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: n8n-ai-postgres
    environment:
      POSTGRES_DB: n8n_ai
      POSTGRES_USER: n8n_ai
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-n8n_ai_dev}
      POSTGRES_MULTIPLE_DATABASES: orchestrator,engine,analytics
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infra/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n_ai"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - n8n-ai

  # Redis Cache & Session Store
  redis:
    image: redis:7-alpine
    container_name: n8n-ai-redis
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
      - ./infra/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - n8n-ai

  # RabbitMQ Message Queue
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: n8n-ai-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-n8n_ai}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-n8n_ai_dev}
      RABBITMQ_DEFAULT_VHOST: /n8n-ai
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./infra/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./infra/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - n8n-ai

  # ClickHouse Analytics Database
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: n8n-ai-clickhouse
    environment:
      CLICKHOUSE_DB: analytics
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-analytics}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-analytics_dev}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9009:9000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - n8n-ai

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: n8n-ai-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-n8n_ai_access}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-n8n_ai_secret}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - n8n-ai

  # Jaeger Tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: n8n-ai-jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"
      - "14268:14268"
      - "4317:4317"
      - "4318:4318"
    networks:
      - n8n-ai

  # Prometheus Metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: n8n-ai-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    volumes:
      - prometheus_data:/prometheus
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./infra/prometheus/rules:/etc/prometheus/rules
    ports:
      - "9090:9090"
    depends_on:
      - orchestrator-nest
      - engine-nest
    networks:
      - n8n-ai

  # Grafana Dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: n8n-ai-grafana
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_INSTALL_PLUGINS: grafana-piechart-panel,grafana-worldmap-panel
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
      - ./infra/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3002:3000"
    depends_on:
      - prometheus
    networks:
      - n8n-ai

  # Orchestrator Service (NestJS)
  orchestrator-nest:
    build:
      context: ./orchestrator-nest
      dockerfile: Dockerfile
      target: development
    container_name: n8n-ai-orchestrator
    environment:
      NODE_ENV: development
      PORT: 3000
      GRPC_PORT: 50051
      DATABASE_URL: postgresql://n8n_ai:${POSTGRES_PASSWORD:-n8n_ai_dev}@postgres:5432/orchestrator
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-n8n_ai}:${RABBITMQ_PASSWORD:-n8n_ai_dev}@rabbitmq:5672/n8n-ai
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-n8n_ai_access}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-n8n_ai_secret}
      JWT_SECRET: ${JWT_SECRET:-super_secret_jwt_key}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-super_secret_encryption_key}
    volumes:
      - ./orchestrator-nest:/app
      - /app/node_modules
      - ./proto-contracts:/app/proto-contracts
    ports:
      - "3000:3000"
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - n8n-ai
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Engine Service (NestJS)
  engine-nest:
    build:
      context: ./engine-nest
      dockerfile: Dockerfile
      target: development
    container_name: n8n-ai-engine
    environment:
      NODE_ENV: development
      PORT: 3001
      GRPC_PORT: 50052
      DATABASE_URL: postgresql://n8n_ai:${POSTGRES_PASSWORD:-n8n_ai_dev}@postgres:5432/engine
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://${RABBITMQ_USER:-n8n_ai}:${RABBITMQ_PASSWORD:-n8n_ai_dev}@rabbitmq:5672/n8n-ai
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-n8n_ai_access}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-n8n_ai_secret}
      JWT_SECRET: ${JWT_SECRET:-super_secret_jwt_key}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-super_secret_encryption_key}
    volumes:
      - ./engine-nest:/app
      - /app/node_modules
      - ./proto-contracts:/app/proto-contracts
      - engine_plugins:/app/plugins
      - engine_temp:/tmp/n8n-ai
    ports:
      - "3001:3001"
      - "50052:50052"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - n8n-ai
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Load Balancer & API Gateway
  nginx:
    image: nginx:alpine
    container_name: n8n-ai-nginx
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infra/nginx/conf.d:/etc/nginx/conf.d
      - ./infra/nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - orchestrator-nest
      - grafana
    networks:
      - n8n-ai
    restart: unless-stopped

  # HashiCorp Vault for Secrets Management (Development)
  vault:
    image: hashicorp/vault:latest
    container_name: n8n-ai-vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_ROOT_TOKEN:-dev-root-token}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    volumes:
      - vault_data:/vault/data
      - ./infra/vault/config.hcl:/vault/config/config.hcl
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    networks:
      - n8n-ai
    command: ["vault", "server", "-dev", "-dev-listen-address=0.0.0.0:8200"]

networks:
  n8n-ai:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  clickhouse_data:
  minio_data:
  prometheus_data:
  grafana_data:
  vault_data:
  engine_plugins:
  engine_temp:
